import Mathlib

/-!
# Challenge: the low individual degree test main theorem

Self-contained comparator challenge for `MIPStarRE.LDT.Test.mainFormal`, the
corrected source statement of `thm:main-formal` — the soundness theorem of the
quantum low individual degree test (Ji, Natarajan, Vidick, Wright, Yuen,
"Quantum soundness of the classical low individual degree test",
arXiv:2009.12982), the central technical ingredient of MIP* = RE.

This file imports **only Mathlib** and re-declares, verbatim and in dependency
order, every definition in the transitive closure of the statement of
`mainFormal`; the theorem itself is stated with `sorry`.  It is the entire
human audit surface: a reader who agrees that this file states the intended
theorem does not need to read anything else.  The
[comparator](https://github.com/leanprover/comparator) tool verifies
mechanically that the [MIPStarRE](https://github.com/LionSR/MIPStarRE)
library declares statements identical to these and proves the theorem using
no axioms beyond `propext`, `Quot.sound`, and `Classical.choice`.

Each declaration carries a provenance comment (`-- source: <file>:<lines>`)
pointing at its origin in the MIPStarRE library, where docstrings cite the
paper passages being encoded.  This file is generated by
`scripts/comparator/` in that repository; see the README alongside this file
for how to run the verification.
-/

open scoped BigOperators MatrixOrder Matrix ComplexOrder
