#!/usr/bin/env python3
"""Report-only freshness checks for the repository README.

The audit is intentionally narrow and conservative.  It checks the README for
local path references that no longer exist, for the documented LDT submodule
count drifting from the repository layout, and for hard-coded Lean / Mathlib
versions that disagree with ``lean-toolchain`` or ``lakefile.toml``.

The tool never edits files.  By default it exits successfully even when it finds
stale content so that scheduled GitHub Actions can stay report-only; pass
``--fail-on-stale`` when a local pre-commit check should fail on drift.
"""

from __future__ import annotations

import argparse
import json
import re
import sys

try:
    import tomllib
except ModuleNotFoundError:  # pragma: no cover - Python < 3.11 fallback
    tomllib = None

from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Iterable
from urllib.parse import unquote, urlparse


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class PathReference:
    """A local path reference found in README prose."""

    path: str
    line: int
    kind: str


@dataclass(frozen=True)
class VersionMention:
    """A hard-coded Lean / Mathlib version mention in the README."""

    tool: str
    version: str
    line: int


@dataclass
class ReadmeAuditReport:
    """Structured README freshness audit result."""

    readme: str
    path_references: list[dict[str, object]] = field(default_factory=list)
    missing_paths: list[dict[str, object]] = field(default_factory=list)
    ldt_submodule_count: dict[str, object] = field(default_factory=dict)
    toolchain: dict[str, object] = field(default_factory=dict)

    @property
    def is_flagged(self) -> bool:
        return bool(
            self.missing_paths
            or self.ldt_submodule_count.get("mismatches")
            or self.toolchain.get("mismatches")
        )

    def to_jsonable(self) -> dict[str, object]:
        payload = asdict(self)
        payload["flagged"] = self.is_flagged
        return payload


# ---------------------------------------------------------------------------
# README parsing helpers
# ---------------------------------------------------------------------------

_FENCED_BLOCK_RE = re.compile(r"^\s*(```|~~~)")
_MARKDOWN_LINK_RE = re.compile(r"(?<!!)\[[^\]\n]+\]\(([^)\s]+)(?:\s+\"[^\"]*\")?\)")
_INLINE_CODE_RE = re.compile(r"(?<!`)`([^`\n]+)`(?!`)")
_RAW_PROJECT_PATH_RE = re.compile(
    r"(?<![A-Za-z0-9_./-])"
    r"((?:\./)?(?:"
    r"README\.md|CLAUDE\.md|lakefile\.toml|lake-manifest\.json|"
    r"lean-toolchain|MIPStarRE\.lean|"
    r"(?:\.github|MIPStarRE|blueprint|docs|references|scripts)/"
    r"(?:[A-Za-z0-9_.-]+/?)*))"
)
_TREE_ROOT_RE = re.compile(r"^\s*((?:\.github|MIPStarRE|blueprint|docs|references|scripts)/)\s*$")
_TREE_ENTRY_RE = re.compile(
    r"^(?P<prefix>[ │]*)[├└]──\s+(?P<name>[A-Za-z0-9_.-]+/?)"
)
_LDT_COUNT_RE = re.compile(r"LDT/[^\n#]*(?:#|//)[^\n]*\((\d+)\s+submodules?\)", re.IGNORECASE)
_LEAN_VERSION_RE = re.compile(r"\bLean\s+(?:v)?(\d+\.\d+\.\d+)\b", re.IGNORECASE)
_MATHLIB_VERSION_RE = re.compile(r"\bMathlib\s+(v?\d+\.\d+\.\d+)\b", re.IGNORECASE)

# Inline-code snippets are treated as local paths only when they are clearly
# project paths.  This avoids false positives from Lean names such as
# ``MIPStarRE.LDT.*`` or commands such as ``lake build``.
_PATH_PREFIXES = (
    ".github/",
    "MIPStarRE/",
    "blueprint/",
    "docs/",
    "references/",
    "scripts/",
)
_TOP_LEVEL_PATHS = {
    "README.md",
    "CLAUDE.md",
    "lakefile.toml",
    "lake-manifest.json",
    "lean-toolchain",
    "MIPStarRE.lean",
}

# Generated by the blueprint sync tooling; useful to mention in README command
# examples, but not expected to exist in a fresh checkout.
_GENERATED_PATH_ALLOWLIST = frozenset({"blueprint/lean_decls"})


def _iter_content_lines(text: str) -> Iterable[tuple[int, str]]:
    """Yield README prose lines outside fenced code blocks."""
    in_fence = False
    for line_no, line in enumerate(text.splitlines(), start=1):
        if _FENCED_BLOCK_RE.match(line):
            in_fence = not in_fence
            continue
        if not in_fence:
            yield line_no, line


def _iter_fenced_content_lines(text: str) -> Iterable[tuple[int, str]]:
    """Yield README lines inside fenced blocks, omitting delimiters."""
    in_fence = False
    for line_no, line in enumerate(text.splitlines(), start=1):
        if _FENCED_BLOCK_RE.match(line):
            in_fence = not in_fence
            continue
        if in_fence:
            yield line_no, line


def _normalize_candidate(candidate: str) -> str | None:
    """Normalize an inline-code or Markdown-link candidate to a repo path."""
    raw = candidate.strip()
    if not raw:
        return None
    if raw.startswith(("http://", "https://", "mailto:", "#")):
        return None

    parsed = urlparse(raw)
    path = unquote(parsed.path)
    if not path or path.startswith(("/", "../")) or "/../" in path:
        return None
    if path.startswith("./"):
        path = path[2:]
    if not path or any(ch in path for ch in "{}<>$\\"):
        return None

    path = path.rstrip(".,;:")
    if not path:
        return None

    if path in _TOP_LEVEL_PATHS or path.startswith(_PATH_PREFIXES):
        return path
    return None


def _append_unique_ref(
    refs: list[PathReference],
    seen: set[tuple[str, int, str]],
    path: str | None,
    line_no: int,
    kind: str,
) -> None:
    """Append a path reference when normalization succeeded and it is new."""
    if path is None:
        return
    key = (path, line_no, kind)
    if key in seen:
        return
    seen.add(key)
    refs.append(PathReference(path=path, line=line_no, kind=kind))


def _extract_tree_path_references(
    readme_text: str,
    refs: list[PathReference],
    seen: set[tuple[str, int, str]],
) -> None:
    """Resolve tree-style fenced README entries to full repository paths."""
    stack: list[tuple[int, str]] = []
    in_fence = False
    for line_no, line in enumerate(readme_text.splitlines(), start=1):
        if _FENCED_BLOCK_RE.match(line):
            in_fence = not in_fence
            stack = []
            continue
        if not in_fence:
            continue

        root_match = _TREE_ROOT_RE.match(line)
        if root_match:
            root = _normalize_candidate(root_match.group(1))
            if root is not None:
                stack = [(0, root)]
            continue

        entry_match = _TREE_ENTRY_RE.match(line)
        if not entry_match or not stack:
            continue
        prefix = entry_match.group("prefix")
        depth = len(prefix.replace("│", " ")) // 4 + 1
        name = entry_match.group("name")
        while stack and stack[-1][0] >= depth:
            stack.pop()
        if not stack:
            continue
        parent = stack[-1][1]
        path = f"{parent.rstrip('/')}/{name}"
        _append_unique_ref(refs, seen, _normalize_candidate(path), line_no, "fenced-tree")
        if name.endswith("/"):
            stack.append((depth, path))


def extract_path_references(readme_text: str) -> list[PathReference]:
    """Extract local path references from README prose and fenced examples."""
    refs: list[PathReference] = []
    seen: set[tuple[str, int, str]] = set()
    for line_no, line in _iter_content_lines(readme_text):
        for match in _MARKDOWN_LINK_RE.finditer(line):
            _append_unique_ref(
                refs,
                seen,
                _normalize_candidate(match.group(1)),
                line_no,
                "markdown-link",
            )
        for match in _INLINE_CODE_RE.finditer(line):
            _append_unique_ref(
                refs,
                seen,
                _normalize_candidate(match.group(1)),
                line_no,
                "inline-code",
            )
    for line_no, line in _iter_fenced_content_lines(readme_text):
        for match in _RAW_PROJECT_PATH_RE.finditer(line):
            _append_unique_ref(
                refs,
                seen,
                _normalize_candidate(match.group(1)),
                line_no,
                "fenced-code",
            )
    _extract_tree_path_references(readme_text, refs, seen)
    return refs


def _repo_path(root: Path, ref: str) -> Path:
    """Return the absolute path for ``ref`` and reject escapes."""
    root_resolved = root.resolve()
    resolved = (root_resolved / ref).resolve()
    if resolved != root_resolved and root_resolved not in resolved.parents:
        raise ValueError(f"README path reference escapes repository root: {ref}")
    return resolved


def missing_path_references(root: Path, refs: Iterable[PathReference]) -> list[dict[str, object]]:
    """Return referenced local paths that do not exist."""
    missing: list[dict[str, object]] = []
    for ref in refs:
        target = _repo_path(root, ref.path)
        if not target.exists() and ref.path not in _GENERATED_PATH_ALLOWLIST:
            missing.append({"path": ref.path, "line": ref.line, "kind": ref.kind})
    return missing


# ---------------------------------------------------------------------------
# Layout and toolchain checks
# ---------------------------------------------------------------------------

def audit_ldt_submodule_count(root: Path, readme_text: str) -> dict[str, object]:
    """Compare README's documented LDT submodule count with the filesystem."""
    ldt_root = root / "MIPStarRE" / "LDT"
    actual = 0
    if ldt_root.exists():
        actual = sum(1 for child in ldt_root.iterdir() if child.is_dir())

    mentions: list[dict[str, int]] = []
    for line_no, line in enumerate(readme_text.splitlines(), start=1):
        for match in _LDT_COUNT_RE.finditer(line):
            mentions.append({"line": line_no, "count": int(match.group(1))})

    mismatches = [mention for mention in mentions if mention["count"] != actual]
    return {
        "actual": actual,
        "mentions": mentions,
        "mismatches": mismatches,
    }


def read_lean_toolchain_version(root: Path) -> str | None:
    """Read the pinned Lean version from ``lean-toolchain``."""
    path = root / "lean-toolchain"
    if not path.exists():
        return None
    text = path.read_text(encoding="utf-8", errors="replace").strip()
    match = re.search(r"v(\d+\.\d+\.\d+)\b", text)
    return match.group(1) if match else None


def _normalize_mathlib_version(version: str | None) -> str | None:
    """Normalize Mathlib revisions to the README-comparison form."""
    if version is None:
        return None
    return version if version.startswith("v") else f"v{version}"


def read_lakefile_mathlib_rev(root: Path) -> str | None:
    """Read the Mathlib revision from the ``mathlib`` requirement block."""
    path = root / "lakefile.toml"
    if not path.exists():
        return None
    text = path.read_text(encoding="utf-8", errors="replace")

    if tomllib is not None:
        data = tomllib.loads(text)
        for requirement in data.get("require", []):
            if requirement.get("name") == "mathlib":
                return _normalize_mathlib_version(requirement.get("rev"))
        return None

    blocks: list[dict[str, str]] = []
    current: dict[str, str] | None = None
    for raw_line in text.splitlines():
        line = raw_line.split("#", 1)[0].strip()
        section_match = re.match(r"\[\[([^\]]+)\]\]", line)
        if section_match:
            if current is not None:
                blocks.append(current)
            current = {} if section_match.group(1).strip() == "require" else None
            continue
        if current is None:
            continue
        kv_match = re.match(r'([A-Za-z0-9_-]+)\s*=\s*"([^"]*)"', line)
        if kv_match:
            current[kv_match.group(1)] = kv_match.group(2)
    if current is not None:
        blocks.append(current)

    for block in blocks:
        if block.get("name") == "mathlib":
            return _normalize_mathlib_version(block.get("rev"))
    return None


def extract_version_mentions(readme_text: str) -> list[VersionMention]:
    """Extract hard-coded Lean and Mathlib version mentions from README."""
    mentions: list[VersionMention] = []
    for line_no, line in _iter_content_lines(readme_text):
        for match in _LEAN_VERSION_RE.finditer(line):
            mentions.append(VersionMention(tool="Lean", version=match.group(1), line=line_no))
        for match in _MATHLIB_VERSION_RE.finditer(line):
            version = match.group(1)
            if not version.startswith("v"):
                version = f"v{version}"
            mentions.append(VersionMention(tool="Mathlib", version=version, line=line_no))
    return mentions


def audit_toolchain_versions(root: Path, readme_text: str) -> dict[str, object]:
    """Check hard-coded README versions against pinned project files."""
    lean_version = read_lean_toolchain_version(root)
    mathlib_rev = read_lakefile_mathlib_rev(root)
    mentions = extract_version_mentions(readme_text)
    mismatches: list[dict[str, object]] = []

    for mention in mentions:
        if mention.tool == "Lean" and lean_version is not None and mention.version != lean_version:
            mismatches.append({
                "tool": mention.tool,
                "line": mention.line,
                "mentioned": mention.version,
                "expected": lean_version,
            })
        if mention.tool == "Mathlib" and mathlib_rev is not None and mention.version != mathlib_rev:
            mismatches.append({
                "tool": mention.tool,
                "line": mention.line,
                "mentioned": mention.version,
                "expected": mathlib_rev,
            })

    return {
        "lean_toolchain": lean_version,
        "mathlib_rev": mathlib_rev,
        "hardcoded_mentions": [asdict(mention) for mention in mentions],
        "mismatches": mismatches,
    }


# ---------------------------------------------------------------------------
# Report rendering
# ---------------------------------------------------------------------------

def audit_readme(root: Path, readme: Path) -> ReadmeAuditReport:
    """Run all README freshness checks."""
    text = readme.read_text(encoding="utf-8", errors="replace")
    refs = extract_path_references(text)
    path_entries = [
        {
            "path": ref.path,
            "line": ref.line,
            "kind": ref.kind,
            "exists": _repo_path(root, ref.path).exists(),
            "allowed_missing": ref.path in _GENERATED_PATH_ALLOWLIST,
        }
        for ref in refs
    ]
    return ReadmeAuditReport(
        readme=str(readme.relative_to(root) if readme.is_relative_to(root) else readme),
        path_references=path_entries,
        missing_paths=missing_path_references(root, refs),
        ldt_submodule_count=audit_ldt_submodule_count(root, text),
        toolchain=audit_toolchain_versions(root, text),
    )


def render_json_report(report: ReadmeAuditReport) -> str:
    """Render ``report`` as pretty JSON."""
    return json.dumps(report.to_jsonable(), indent=2, sort_keys=True) + "\n"


def render_text_report(report: ReadmeAuditReport) -> str:
    """Render ``report`` as a human-readable summary."""
    payload = report.to_jsonable()
    lines = [
        "README freshness audit",
        "=======================",
        f"readme: {payload['readme']}",
        f"flagged: {payload['flagged']}",
        "",
        "local path references:",
        f"  checked: {len(report.path_references)}",
    ]
    if report.missing_paths:
        lines.append("  missing:")
        for item in report.missing_paths:
            lines.append(f"    - {item['path']} (line {item['line']}, {item['kind']})")
    else:
        lines.append("  missing: none")
    allowed_missing = [
        item for item in report.path_references if item.get("allowed_missing")
    ]
    if allowed_missing:
        lines.append("  allowed generated paths:")
        for item in allowed_missing:
            lines.append(f"    - {item['path']} (line {item['line']}, {item['kind']})")

    ldt = report.ldt_submodule_count
    lines.extend([
        "",
        "LDT submodule count:",
        f"  actual: {ldt.get('actual')}",
    ])
    mentions = ldt.get("mentions", [])
    if mentions:
        lines.append("  README mentions:")
        for mention in mentions:  # type: ignore[assignment]
            lines.append(f"    - line {mention['line']}: {mention['count']}")
    else:
        lines.append("  README mentions: none")
    if ldt.get("mismatches"):
        lines.append("  mismatches:")
        for mismatch in ldt["mismatches"]:  # type: ignore[index]
            lines.append(
                f"    - line {mismatch['line']}: README says "
                f"{mismatch['count']}, actual is {ldt.get('actual')}"
            )
    else:
        lines.append("  mismatches: none")

    toolchain = report.toolchain
    lines.extend([
        "",
        "toolchain versions:",
        f"  lean-toolchain: {toolchain.get('lean_toolchain') or 'unknown'}",
        f"  lakefile mathlib rev: {toolchain.get('mathlib_rev') or 'unknown'}",
    ])
    mentions = toolchain.get("hardcoded_mentions", [])
    if mentions:
        lines.append("  hard-coded README mentions:")
        for mention in mentions:  # type: ignore[assignment]
            lines.append(f"    - line {mention['line']}: {mention['tool']} {mention['version']}")
    else:
        lines.append("  hard-coded README mentions: none")
    if toolchain.get("mismatches"):
        lines.append("  mismatches:")
        for mismatch in toolchain["mismatches"]:  # type: ignore[index]
            lines.append(
                f"    - line {mismatch['line']}: {mismatch['tool']} {mismatch['mentioned']} "
                f"!= {mismatch['expected']}"
            )
    else:
        lines.append("  mismatches: none")

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path("."), help="repository root")
    parser.add_argument("--readme", type=Path, default=Path("README.md"), help="README path")
    parser.add_argument("--format", choices=("text", "json"), default="text", help="output format")
    parser.add_argument("--output", type=Path, help="write report to this path instead of stdout")
    parser.add_argument(
        "--fail-on-stale",
        action="store_true",
        help="exit nonzero when stale README content is detected",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    """CLI entry point."""
    args = _parse_args(sys.argv[1:] if argv is None else argv)
    root = args.root.resolve()
    readme = args.readme
    if not readme.is_absolute():
        readme = root / readme

    report = audit_readme(root, readme.resolve())
    rendered = render_json_report(report) if args.format == "json" else render_text_report(report)

    if args.output:
        args.output.write_text(rendered, encoding="utf-8")
    else:
        sys.stdout.write(rendered)

    return 1 if args.fail_on_stale and report.is_flagged else 0


if __name__ == "__main__":
    raise SystemExit(main())
